### ISSUE TITLE
[refactor]: Remove the unused import statements in vue-scanner.ts.

### ISSUE THREAD

**Issue by ravut8** [logicspark/berryjam#5]
### Overview
I have identified that certain import statements are not being used in any part of the file. This can cause confusion in the future.

https://github.com/logicspark/berryjam/blob/aec7ac576375faf5f3b5fdbe8709ba81cf771aa7/src/vue-scanner.ts#L4

https://github.com/logicspark/berryjam/blob/aec7ac576375faf5f3b5fdbe8709ba81cf771aa7/src/vue-scanner.ts#L6

### Expected Behavior
Remove both of them

**Comment by k7kaushal** [comment]
Hi @ravut8, 
I've been interested in working on open-source projects for quite a while now, Hacktoberfest seems to my starting point in this journey ahead, being new to open-source I feel your issue is a good first contribution for me to start with.
I would like the opportunity to contribute to this issue.

**Comment by ravut8** [comment]
Hey @k7kaushal,
Thanks for the interest. You are more than welcome to try. To get started, please review [our contributing guideline](https://github.com/logicspark/berryjam/blob/main/CONTRIBUTING.md).
If you have any questions, please let us know.
